# Generated by Django 5.2.8 on 2025-11-13 12:52

import django.db.models.deletion
import eventos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('data', models.DateTimeField(verbose_name='Data e Hora')),
                ('local', models.CharField(max_length=300, verbose_name='Local')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo_acesso', models.CharField(default=eventos.models.gerar_codigo_acesso, max_length=8, unique=True, verbose_name='Código de Acesso')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_principal', models.CharField(max_length=200, verbose_name='Nome do Convidado Principal')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('declinado', 'Declinado')], max_length=10, verbose_name='Status')),
                ('total_pessoas', models.PositiveIntegerField(default=1, verbose_name='Total de Pessoas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
