# Generated by Django 4.2.11 on 2025-11-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Sim, irei'), ('declinado', 'Não poderei ir')], max_length=10, verbose_name='Status'),
        ),
    ]
