# Generated by Django 6.0.3 on 2026-04-07 15:00

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_resposta_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='codigo_acesso',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='evento',
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_resposta',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da Resposta'),
        ),
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo do Acompanhante')),
                ('documento', models.CharField(max_length=50, verbose_name='Documento com Foto (RG/CPF)')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='eventos.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_destinatario', models.CharField(blank=True, help_text='Ex: Família Silva (Opcional)', max_length=200, null=True, verbose_name='Nome do Destinatário')),
                ('codigo_acesso', models.CharField(default=eventos.models.gerar_codigo_acesso, max_length=8, unique=True, verbose_name='Código Único do Convite')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='eventos.evento', verbose_name='Evento')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='convite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='eventos.convite', verbose_name='Convite'),
        ),
    ]
