# Generated by Django 6.0.3 on 2026-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_options_alter_resposta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/', verbose_name='Banner do Evento'),
        ),
    ]
